version: '3'
services:
  mysql-standalone:
    image: 'mysql:latest'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=aircnc_db
    ports:
      - "3307:3306"
  demo:
    image: app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql-standalone:3306/aircnc_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    build:
      context: "./"
      dockerfile: "Dockerfile"
    depends_on:
      - mysql-standalone